### ISSUE TITLE
"$ sudo npm install forever -g" resulting in missing argument error

### ISSUE THREAD

**Issue by HogwartsAdmin** [foreversd/forever#1045]
When I run the command "$ sudo npm install forever -g", I get this error log.

npm ERR! Linux 4.15.0-1051-aws
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "forever" "--global"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code EMISSINGARG

npm ERR! typeerror Error: Missing required argument #1
npm ERR! typeerror     at andLogAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:31:3)
npm ERR! typeerror     at fetchPackageMetadata (/usr/share/npm/lib/fetch-package-metadata.js:51:22)
npm ERR! typeerror     at resolveWithNewModule (/usr/share/npm/lib/install/deps.js:456:12)
npm ERR! typeerror     at /usr/share/npm/lib/install/deps.js:457:7
npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror     at /usr/share/npm/lib/fetch-package-metadata.js:37:12
npm ERR! typeerror     at addRequestedAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:82:5)
npm ERR! typeerror     at returnAndAddMetadata (/usr/share/npm/lib/fetch-package-metadata.js:117:7)
npm ERR! typeerror     at pickVersionFromRegistryDocument (/usr/share/npm/lib/fetch-package-metadata.js:134:20)
npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror This is an error with npm itself. Please report this error at:
npm ERR! typeerror     <http://github.com/npm/npm/issues>

[npm-debug.log](https://github.com/foreversd/forever/files/4007752/npm-debug.log)

**Comment by kgmayani** [comment]
facing same issue.

**Comment by kgmayani** [comment]
error argv "/usr/bin/node" "/usr/bin/npm" "i" "forever" "-g"
error node v8.10.0
error npm  v3.5.2
error code EMISSINGARG
error typeerror Error: Missing required argument #1
error typeerror     at andLogAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:31:3)
error typeerror     at fetchPackageMetadata (/usr/share/npm/lib/fetch-package-metadata.js:51:22)
error typeerror     at resolveWithNewModule (/usr/share/npm/lib/install/deps.js:456:12)
error typeerror     at /usr/share/npm/lib/install/deps.js:457:7
error typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
error typeerror     at /usr/share/npm/lib/fetch-package-metadata.js:37:12
error typeerror     at addRequestedAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:82:5)
error typeerror     at returnAndAddMetadata (/usr/share/npm/lib/fetch-package-metadata.js:117:7)
error typeerror     at pickVersionFromRegistryDocument (/usr/share/npm/lib/fetch-package-metadata.js:134:20)
error typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
error typeerror This is an error with npm itself. Please report this error at:
error typeerror     <http://github.com/npm/npm/issues>
verbose exit [ 1, true ]

**Comment by canmingir** [comment]
I am having the same problem, here are details:

Ubuntu 18.04 at AWS
Node 8.10.0
NPM 3.5.2

`sudo npm install forever -g`
npm ERR! Linux 4.15.0-1051-aws
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "forever" "-g"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code EMISSINGARG

npm ERR! typeerror Error: Missing required argument #1
npm ERR! typeerror     at andLogAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:31:3)
npm ERR! typeerror     at fetchPackageMetadata (/usr/share/npm/lib/fetch-package-metadata.js:51:22)
npm ERR! typeerror     at resolveWithNewModule (/usr/share/npm/lib/install/deps.js:456:12)
npm ERR! typeerror     at /usr/share/npm/lib/install/deps.js:457:7
npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror     at /usr/share/npm/lib/fetch-package-metadata.js:37:12
npm ERR! typeerror     at addRequestedAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:82:5)
npm ERR! typeerror     at returnAndAddMetadata (/usr/share/npm/lib/fetch-package-metadata.js:117:7)
npm ERR! typeerror     at pickVersionFromRegistryDocument (/usr/share/npm/lib/fetch-package-metadata.js:134:20)
npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror This is an error with npm itself. Please report this error at:
npm ERR! typeerror     <http://github.com/npm/npm/issues>

**Comment by deusilva** [comment]
Same error from me too

**Comment by oguzkulcu** [comment]
I am having the same problem.

**Comment by vivekvkt123** [comment]
I am facing the same issue. Please fix this

**Comment by oguzkulcu** [comment]
I found the solution. Fixed issue when updating npm version.

npm old version: 3
npm update version: 6.7.0

**Comment by canmingir** [comment]
Can't believe Ubuntu's repo is so much behind,

This worked for me:
https://www.digitalocean.com/community/tutorials/how-to-install-node-js-on-ubuntu-18-04

**Comment by IngwiePhoenix** [comment]
Excuse me, but I believe this is a NPM issue, not a Forever one?

Since it is reporting missing arguments, try running it through `sudo -s` or outright login into your root account and see if that changes. Also, try shifting around the positionals. From my past experience with NPM, it always seemed to do better with the `-g` flag being specified as the first-most argument: `npm -g install forever`.

**Comment by Exius99** [comment]
Solved my issue with IngwuiPheonix's fix.

`sudo -s install forever -g`

**Comment by sjodin** [comment]
@Exius99 What did you do exactly? You changed `npm install forever -g` to `npm -g install forever`?

**Comment by Exius99** [comment]
@sjodin What I did was take part of IngwiePhoenix's suggestion of replacing the positionals and added the `sudo -s` before it as well to get the exact command: `sudo -s install forever -g`

This adds and moves around several of the commands parameters.
Try copying that directly and pasting it in the command line.

**Comment by sjodin** [comment]
Seems like forever is dependent on deep-equal which recently introduced some incompatibility with the old version of npm. Here is what I did to get around it:
`npm -g install forever deep-equal@1.1.1`

**Comment by Aubizzy** [comment]
this worked "npm -g install forever deep-equal@1.1.1 "

**Comment by yakkomajuri** [comment]
Awesome! That was it. Reiterating:

`npm -g install forever deep-equal@1.1.1`

**Comment by enniosousa** [comment]
@sjodin you're the best! Thank you so much!

**Comment by kibertoad** [comment]
Can you try forever 3.0.0?

**Comment by CodeWithJD** [comment]
> Seems like forever is dependent on deep-equal which recently introduced some incompatibility with the old version of npm. Here is what I did to get around it:
> `npm -g install forever deep-equal@1.1.1`

Great That's work save a lot of time.
