### ISSUE TITLE
Cannot find module '/x/y/z/log'

### ISSUE THREAD

**Issue by igorescobar** [foreversd/forever#517]
Hi guys...

When I'm starting an node.js with forever I'm getting this weird error about an log module.

This is the command:

``` node
/usr/local/bin/forever start /app/gateway/current/app.js -w -m 1000 -l /app/logs/gateway/forever.log -o /app/logs/gateway/out.log -e /app/logs/gateway/err.log -n 30 --minUptime=1000000000
```

And this is the output:

```
warn:    --minUptime not set. Defaulting to: 1000ms
warn:    --spinSleepTime not set. Your script will exit if it does not stay up for at least 1000ms

module.js:340
    throw err;
          ^
Error: Cannot find module '/app/gateway/current/log'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3
error: Forever detected script exited with code: 8
```

If I ran the `app.js` with the node command instead of forever... the error doesn't occur...

Any ideas?

node version: v0.10.23
forever version: v0.10.11

**Comment by ediazv** [comment]
This is a response to executing "forever log", and not "forever logs"
It's trying to execute a "log" module, which not exists
