### ISSUE TITLE
Forever documentation about .foreverignore

### ISSUE THREAD

**Issue by ilanbiala** [foreversd/forever#590]
I got this error:

```
error: Could not read .foreverignore file.
error: ENOENT, open '/var/www/ilanbiala.com/public_html/.foreverignore'
```

but I can't find docs about .foreverignore. What goes in there?

**Comment by levelicarus** [comment]
I am also getting this issue. I'm also curious if there has been any progress on this issue!

**Comment by NawarA** [comment]
I got it working. Add .forever in the directory you're watching, then add

**.log** 

to the file, or whatever file pattern you'd like to ignore. Thats it. I'm using this now

**Comment by ilanbiala** [comment]
@indexzero any documentation added for this?

**Comment by mikeatlas** [comment]
@ilanbiala no documentation yet, author is requesting/welcoming a PR for documentation of the feature per #663

**Comment by ilanbiala** [comment]
Not really sure why...if it's so simple then someone who maintains the package really should have written the initial docs.

**Comment by indexzero** [comment]
@ilanbiala it is equally as simple for a new contributor to write up this documentation. Open source is by definition a collaborative effort. Simply expressing negative sentiments and not contributing will not motivate a maintainer to do work. The dark side does not win here. 

PRs are still very welcome here.

**Comment by mikeatlas** [comment]
It's a complicated documentation task, apparently - it appears are complications and nuances with the overlapping behaviors of the `--watch`, `--watchIgnore`, and `--watchDirectory` CLI switch functionalities that are (subtly) coupled more tightly than they could be along with the behavior of the `.foreverignore` file. What takes precedent? 

I presume this is why nobody has offered to submit a PR for documentation _and_ the original author isn't inclined to put effort into it either. It requires more than just editing the `README.md` to correctly document the behavior; one would have to read the source code for all these switches and understand the true behavior of all the potential variants (other tickets have demonstrated there's only scant test coverage for this feature as well) lackiing... for years.... I suppose as the original author I'd be disinclined to want to fix, maintain, and properly document this complicated aspect. 

It might help to seek out additional willing maintainers @indexzero to help?

Also, there _is_ precedent for the author [accepting documentation PRs](https://github.com/foreverjs/forever/pull/776), it's just that most people expect that core functionality is documented when added or changed by the original author _or the contributor; and it's not the case here it seems that many features have been contributed and accepted over the years; yet not all of it got `README` love.

**Comment by darwinFailure** [comment]
updates on this? looks like the `--watch` flag brakes forever when running inside the latest WebStorm IDE (2016.2). Anyone into this?

[Here](https://intellij-support.jetbrains.com/hc/en-us/community/posts/207697605-Forever-js-in-WebStorm-2016-2) is my post on the WE tech support page.

**Comment by danger89** [comment]
Yea it's still not solved actually..
```
error: Could not read .foreverignore file.
error: ENOENT: no such file or directory, open '/.foreverignore'
error: restarting script because unlinkDir changed  
events.js:141 
      throw er; // Unhandled 'error' event
      ^ 
Error: watch /lost+found EACCES 
    at exports._errnoException (util.js:907:11)   
    at FSWatcher.start (fs.js:1234:19)
    at Object.fs.watch (fs.js:1262:11)  
	
```

**Comment by simondass** [comment]
I've not added anything to my .foreverignore file so cannot comment on the correct format, but I was getting this error until I; 
a) Created an empty .foreverignore in my project root 
b) Used the --watchDirectory option and set it to my project root
i.e. `forever -w --watchDirectory ./ myscript.js`

Obviously change the watch dir as required.

**Comment by askanhan** [comment]
> I've not added anything to my .foreverignore file so cannot comment on the correct format, but I was getting this error until I;
> a) Created an empty .foreverignore in my project root
> b) Used the --watchDirectory option and set it to my project root
> i.e. `forever -w --watchDirectory ./ myscript.js`
> 
> Obviously change the watch dir as required.

can't do that since creating a file starting with '.' is not permitted in Windows...
